---
apiVersion: v1
data:
  config.json: eyJhdXRocyI6eyJpY3IuaW8iOnsidXNlcm5hbWUiOiJpYW1hcGlrZXkiLCJwYXNzd29yZCI6Im84Vkt5ajJBbkZQQXBtdUtIb29fcm51VHJkWFVBQVVKdElvYTRKaVMyanBNIiwiZW1haWwiOiJuYWRnb3dkYUB1cy5pYm0uY29tIiwiYXV0aCI6ImFXRnRZWEJwYTJWNU9tODRWa3Q1YWpKQmJrWlFRWEJ0ZFV0SWIyOWZjbTUxVkhKa1dGVkJRVlZLZEVsdllUUkthVk15YW5CTiJ9fX0= 
kind: Secret
metadata:
  name: img-registry-secret
type: Opaque
